on:
  push:

jobs:
  build:
    name: build rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v4
    - name: install rustup
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: install linux deps
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libwayland-dev wayland-protocols libxkbcommon-dev libasound2-dev libudev-dev
    - name: build
      run: |
        cargo build --release --target ${{ matrix.target }}
    - name: upload
      uses: actions/upload-artifact@v5.0.0
      with:
        name: ${{ matrix.target }}
        path: target/${{ matrix.target }}
    
    
