on:
  push:

jobs:
  build:
    name: build rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
    - uses: actions/checkout@v4
    - name: install rustup
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -- -y
    - name: build
      run: |
        cargo build --release
    - name: upload
      uses: actions/upload-artifact@v5.0.0
      with:
        name: ${{ matrix.target }}
        path: target/release
    
    
